# Generated by Django 5.1.15 on 2026-09-23 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("STARTER", "Starter"),
                            ("PROFESSIONAL", "Professional"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("max_doctors", models.PositiveIntegerField(default=1)),
                ("max_staff", models.PositiveIntegerField(default=2)),
                ("max_branches", models.PositiveIntegerField(default=1)),
                ("max_monthly_appointments", models.PositiveIntegerField(default=100)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("CANCELLED", "Cancelled"),
                            ("TRIAL", "Trial"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="organizations.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
