# Generated by Django 5.1.15 on 2026-09-23 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "medical_registration_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("specialization", models.CharField(max_length=255)),
                (
                    "qualification",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("biography", models.TextField(blank=True, default="")),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("experience_years", models.PositiveIntegerField(default=0)),
                ("languages", models.JSONField(blank=True, default=list)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="doctors/"),
                ),
                ("active", models.BooleanField(default=True)),
                ("verified", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="doctors",
                        to="organizations.department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "specialization"],
                        name="doctors_doc_organiz_3d80f1_idx",
                    ),
                    models.Index(
                        fields=["organization", "active"],
                        name="doctors_doc_organiz_c4f299_idx",
                    ),
                ],
            },
        ),
    ]
